/**
 * 1657. Determine if Two Strings Are Close
Medium
Topics
Companies
Hint
Two strings are considered close if you can attain one from the other using the following operations:

Operation 1: Swap any two existing characters.
For example, abcde -> aecdb
Operation 2: Transform every occurrence of one existing character into another existing character, and do the same with the other character.
For example, aacabb -> bbcbaa (all a's turn into b's, and all b's turn into a's)
You can use the operations on either string as many times as necessary.

Given two strings, word1 and word2, return true if word1 and word2 are close, and false otherwise.

 
 */

function closeStrings(word1: string, word2: string): boolean {

    if (word1.length !== word2.length) return false;

    let map1 = new Map<string, number>();
    let map2 = new Map<string, number>();

    for (let c of word1) {
        map1.set(c, (map1.get(c) ?? 0) + 1)
    }

    for (let c of word2) {
        map2.set(c, (map2.get(c) ?? 0) + 1)
    }

    for (let v of map1.entries()) {

        let key = v[0]
        let count = v[1]

        if (map2.has(key)) {

            let count2 = map2.get(key)
            if (count == count2) {
                continue;
            }

            for (let v2 of map2.entries()) {
                let k = v2[0];
                let count2 = v2[1];
                if (count2 == count && map1.has(k)) {
                    map2.set(k, map2.get(key)!!)
                    map2.set(key, count2)
                    map1.delete(key)
                    break;
                }
            }

        }
        else {
            //console.log(key)
            return false;
        }
    }

    console.log("dasds")
    console.log(map1, map2)
    console.log("dasds")

    for (let a of map1.entries()) {

        let k = a[0]
        let v = a[1]
        let v2 = map2.get(k) ?? -1


        if (v !== v2) {
            console.log(k, v, v2)
            return false
        }
    }

    //console.log(map1, map2)

    return true;
};


console.log(closeStrings(
    "eexxxxeyyxxxxxxhxxkxicxyxxxeexxxkxxxwxyxxexxxxxxxxxxxxxcxxxxexjxexxxxeexexxhxeitxtexxxkxeexteexxeyxxxxxxxxxfexxqexxxxxxeyexxxyexexhxkxxxuexyxexxxexxeexyxxxxxexxxxxxyxxxxexeexaxxexxeexcxxxxexexejeehxkqwxhxxxexxxtxxxxkxxexxwxxxxxxxxxexyxxexexxxxxxjxxyxxxyxxxxxxxyaxxxxexxxjxxxxxeyoxyxxxxxxxkiyxxixxxeeyxxtxxxexeyeexexxkyxxxexxxxxxxexxxxyxxxxxxexayxxexxcxxwxhyyexxxxuxxxxxexxxtyexexxxxxxxxxxxexxxcxxxxeyxexxxyyeexeexjxxkexeexxxxxxxxjeexxxxxxxyxeyxxxxxexyxjxjxexxxxxekxxxyxxyexxxxxxfyxjxxexxhjxxxxxhxxxxxxxxejxxxxxkxtxxxexcexyyejexexxjxehmxyyhejiexexextxixexxxxxxxxxxyxxxxexxxykxyxxxexxiexxxxxxxxxxxexeyxxyxkxuxexexyxeyaxexxxexxxxxxekxxxxxxnxeyxxxxxyxhexycmxxxtxxexxxxxexjxxxkxexxigexexkxexxxyexxyxxxexxgkyxxxxxxxxyxeeexhxxxxiyeyxqehexxxhxxxxyxxxexexxxxxkeexyoxxxxexxxxxeyxxxxxekxeeyxyeyyxxoqkxixxeuxxxkaxixyxxxxxexxkxxxxxexxxxyejxxxxkxxefxxeaexxeyhexexxexxxexxxxxxxxhjftwxxxydexxxxwexxxxxtexeextixkxxyyxeexxxxxxxyeuyexxjxyxxxxkxxxxxeeexxuehyxxxxyxxxaxexxeyxxxexqxxxxxyyaxtexexeyxxexkexxaoexxkxxxxxxxekxxxxxexexxxeexxxteeoeexxxeeexxxxyqyexeyxxxexxxoxxxixxxxxxexxyxxoexxxwxxxxxexxxexxxexxxxkexeqxxeexxxuixexxxxexkoxxeexxxxxxoekdxxexexxxxxxxxxxxxtyxxxxkqexxyyekxxxxmxxxxeeyyxyyyxexeexxxexxsxjqxeyxxyeexxxxxxxxoxxxxeyxxkixtexxixexxexxxxkyxxxexxxxxxxexexxjyxxxeeixexxkeexxeexxhxyexeeuxxxxoxxxwextxxxyexxxxexxxxuxxxxexxxxxxkxxxetxyhxxkwxcxxjxxxegyxyxexxyejyexxxxxxxxxxkxxxxexxxxweixxxexxxxxyxxexeyexxxxxenjxexyxxexyexxxxxxxebxxexkxxeewxqhkxjxexxxeyexwyxxxxxxeexxjxxxxiextxkxxxexxxxxxexqxxxxxeeexxxxxxsxxxhyxxxxxxxexxxxxxxxxxxexxxxextxxxxxxxkxxkeeeeykxxeyjxkeecxxxxexxyxxexkxxxxxxxxeyxexxxxxxexxxhxxexxeexxetekyyxxxkxqxexxxyxxeexxxxyxeteayexaeyexxxxxxeexxxexoxxxhxeeyjxxjkkxxxexxexxxxxexxxeewxyexejyxxxexexxxxxeexxkxyxjxexxxxxxexxxhxyxxexoexejoxyxxxxxxxxyxxxxexeexxeexxxxxxaxexykexexxxxxxxxexexejxgeexxyxxxxtxeyxxeexeyxxxxxxexwexxxxxkxxexxkxxxxxxxxjxxxyxxexwxxyxxkxexxxxexxxexxxexyxxxxxxxexyyxextkhxxwxxyxxxxxxxxxxxyxexxxxwxuexxxxxxreexexjxxxxxwqtexxxeexxxuxxxxxqxvykxxxxeexxxexeetxexxxyyeexxxeetxxxxxxxxxjxxxxxhxexexxqxexxexxxxxxexxxexxxexxeexxxeexykxxyeeuxxxxxxexxiyhxjyxxxxxeexuxxjkxeexxxyxxxxxexeexxwxxxxyxkexxxiexxxxxxxxyxtxxxxkxxxxetxxxeexeekxxhxexexexieyexxxyaxxxeexxxyexxexxixxrwxxeeyxxxyxxkexxtxxxxxexxxxxxxcxxxxixyexxxexeyexnxxxyxxxxxjeykxejexxxexxjxxjyeyxxxxhxyhxxexqxtexxyyeeyxxxxxxeeqxxxxxxxxjxyxxexktxezyeexkfxkkxxhxjexxxxixxxexxxxxeexetwxeexxxxxxeexyxxexehxixkxxxexyxhxxxxxkxteixybxxxytxxeekxxexexyxxejexexxxjexlhxxxeatxxkxkxxxxxxpxexxxexxtxxxxxxtkxexykkeyaxxexxxxxxxexngxxeexxytxxexyxxexhexxexxexexxxyxywkxxxxxxhxekxxxexhixxxyxeexxxyxxxxyxxxxyxxxxxexxkxextyxxxxexxxxktxnxxkxxxeyxxxxewexxxxxyxkhuyhxexxxxxxxxxexjxxxxxgxxxexyewxexexhxxxxexxxxxyxkxxxyyxxxxgkxxxxxxxxxxxxxexuxxeeyxexqyyxjxxkxxeyeexxxxxxhxxxxxwxxexxexekxexehxxxxkxxxxxxexexxeeexxexxexxxeeeexxexxxxxxhuxewyxxxeetexxxexeeexxfxxeyxyfxxxyxxrxxxxxxxxxkxxxxxxxxxexexxexeejexxxxxxxtxyheaxxxexxexxxxexxxxexxxxxxkxxxxxexexxxxxxxoxxhxxxkxxxxxxhxxxxjxxexyxywtxxxxxfxxxxkxeetxxtjeoxxexxyeeeeexxqxxxxxxixxxxxekxxxaxkxewxyixexxxxtxyxyxxxeyexxexyxkxxxxxxxxxxxxexexexkejetxehexxxqxxaxxxcxxxkxxxeexxexxxxxtyxexkxnxxxxxxekkxxxxeexzxyxxxxxxxxxxxxyeeexxxxxexxxyxexxxxxxxxxyxkxxeyxxxxxxxxyxxkexxixxyexyxyewxeexxxxjxxfkxxxzyxxxxxxxxxxeyxxxjxoexxxxxxexxxtxitxxeaexxxxeaxteexexexeixxxxcxhxxexexnexxxxexxexxjxxxxeeyeyejqkxxxxkxchxxexaxxyexcxxxxxxxxeexykxxeexxxkxxxxxxyxxxxxxkxxyxexexxxxxxaxnxxxiwxxexxxceykxxxexexxxxxxxxoeexeekexykxxexkxxxexjexxxyxxhxxeexxxxxxyxxexixxxxxxxxxxexxyxxyxxxhxxxexxxxxxxxxxxxyxyxxpynxxxkkxixxwxxkxxxexexyexxxxxeyxxyxjieeeyxyxxkqxxytexxxxexxxxxxyehxxsexxxexeexyxxoexxetexexeexxyeuxeexxxxxxxyxyxenxxwxxkaxxxeyxxexxeextxwxxexxxxexxxtexyxxxqexyeekxkxxxxxexxexxeeycxxexxxxxjxykxxexxxxeexxxyxyxxxxxxxxyxauexxekxexxexkxxxjxyeeueyenkxjxxxxxxxyjxhxxxxdjxexhxxxexxexxxexxxxyxxxxtxqixxexxxyxxxxxxkexexixxxxxeyoxeexxxyxxxxxecxxedxxxxxxkxyyxxxxeeyxxyxexxxxxxwxexxxxeyxyxekwxexxkxixxxxxeuhxxxxxxxxhxxexxxyexixxexxxexyykxxkxxxkxuxexkeiyheyyxexexexeyyxxxyxxxoexexcxexxxeyxexfxteqxxxxexxxxxxxexxxyyxeexexxewjxxxxyxxxxxxexxtyxheexexexxejxxxexixeexxkexxxekeexxwxxeexxatxu",
    "bbbcqbbbbqbbcqjjbbbbbcbcjbjqtbqbbbbbcbbbqbbccbcbnbqbbbbbbbbbbbkbbbbqcjbbbcbbbbbjbcjgbbbqbbgcbdcbcccbcbbjxbqbbbbqbbbqtbbbbqcbbbbcccbbbbebbbbbbbcbbbebccibbebbhcxbbcbbbbbbcbbqbrbkbcbqbccxbccbbbqbbibbbbbbbbbbbbbbcjtcbccqqbbcbbjcbxqbbbbtjbbbtbbbjbbibkbccbbjbbtbbrbbjbbvbbbdbbbcxbbbcbbqcbxbbbbpbbjbbqcbcqcbbbbbbbbcbbbbbbbcjbjbbcbbcqbcbqdbqbcnbbbbbbbbbbcbbbbqbbjccbjbrbbbbbbbcbbbcbjbbbbbbbbbbcbcjbqbbcccbbbcbbdbbjbqrjqcbbbbrcjnqcbtcbbqbbcbvebbbbqbbbxbbqbcbbbbbcqbbbbbbbcbbcbbbbbbbbbbccbtcbbbcbbbbbbbccbbbbtbjcbbbbbbbbijxcbbtcbbkbjbbbbbbcbbbcbbcccxckcjqbtnbebbbbcbmrbbbbkctbbbbbbbbbjqbbcbrbcbbtbxbbbbrbbnbbbbqcbcbcbbbkbbbxkqbbbcbcbbbbcbbvbbcbbubjqbbcrbbxbbqbbbcbbqbbbbcbbbjccjbbcbqbcmbcqbbbcbrrbbbqbzbbbbcbcbebcebbbbbbbbnbbbbjnbbctbbbbvbbbbccbbqbbbcbbqkcjbbbbqkcbqbcbcbcbbbcbbbkdbbbvbcbjccbbkbbbbbbbcbbjbbbbfbcbqdbcbbbbbqttbbbbbbabbxjqbbbbbbbbcbccbbbbbbcbbjbxqbbbckbbbrbcbccbbbbbecqcbbbbcqbzbbbbbcbcbcbbcnbbbbblbcccnbbbcbbbjccbbbbcbbbccbcbcccbcbbbbcbjjbbbbqbbbcbcbbbrbcqdbtnbbqbcbbmbjcvbbqbqbbjbcbbbcrbbsbbqcdbbcbbbbbbbibbbbbbbbbbbcybccbbbcbcbbbbbbbbcbbbbqcbbbqbbbkbcvbckcjtbcxbbybxqbcbbbbbdbbbqbbbbbbbbbbbckbjcbbbbccbjbbbrbccbbbbbkbbccxcbbbbbbbbctbbcjbqbcbbcbcbcbbbbbjbbbqccbcbbjbcqbbbbbbcbbbjncqcbcbqbbbqbbbcbbbbbbocbbcbcbbbtcqbqbcbqbqbbbbbebbbbbbqvbcccbbqbbbbbcbbbcbcbicbcqbbcbbbbbcbbcbbbbbbcxbbbbbbbccbbbbcbcbqbbbjbcbcbjbbbbbjbbbbbvbcqqdbbjbcbbbbctbbbbbbbcbbcbcbgbbcbbqbccbbbqqbcbbqbbbqbcbqbjbbbbcbbbqbbjgbbbbbnbbccbbibbbbqqcbbbcbfbbbrlbbrbbbrqbbbbbbbjbbbtbbbbcbbbbnnbbbbqbgbkjtbbcbbbrbbbbcqjbbbjiccccjbqqbjbbbbbbbbbbqbbbbbbbbbbbtbbccbbcbjbbbbcbbbqxbcbrtbccbbjbqbrbbbbcbcbbbbbbccbbbbcbctbbbbcjtcbbbjccqbbbctbcbbkbbbbqbcbbbbcbcxbbybbbgbjjjbbbbcqcbbbbbqrcbbbbqcpbbbgbbxbcvbbbtbkbbotcbnbcjbbbccbbbbbbbcbbbbbbbbbcbbbcbbbbbcbqbqjbbxbbbbbbbbbbbbbcbbbbjbqqbbbcbbbqkxrjbbeqbbcbcbjbbbbcbcgcbbbnfbbbbrbrbcqqbbbxqqbbbbqbbrbbbkbrccbcbbcbbbcbbxccbbbbbbbbccbbmxqbcbxbbqjqbccbbbqbjqbbqcbbbcbcbvbbbcbbbbbbbbbbqjbbbjbbbbbvjbbbpbqqxcbqjvbbbbbcbxqcbcbbbbqcbbjbbbcbbjbbxbbxbqqbbqblcbbbqbcqbkbcrbbcbjbnkbqccbibbkcqbbbcbbbcncbbbbqccbtbxcqbcbbbbqbqqbbbcbxbqcbbbcbbbbbbbbbbcbtcbbbbccbbcbbcbbbbbbbcbbcbbbbbbbbcbtccbdcqbbcrcdbdkbbbbdbbbbbccgbbjbbcnbbbvtbbbcbbbbcbbibbcbbqbbbbbbbcbbbbnccccbbcicbbbbbbbccbcbbbbbbbbkbtdbbbbdbrcbbbbbtbmbbbccbbbqcbbcbcbqqtbqbcqqbcbcqbbccbbxxbncqbbbbbbbrbebibcbjtjxcccjbcbkbjcbbcxbicqbbccbbccbbcjbcbcqccbxbbbbcbcbcjbbbcbbcqcqqnqjcbbckbbtcbbcqcbbcrbbbbkbbqjbbcbcbbcbbebjbcdbbcbbrbqbbbbbbcbcbgbbcyrqccbbbbbbbbbbccbcqxcbbbbqbcbubbbccqcqbjccbbbqbbcbccbbcccbbarbrbcbcbcbcbbnqbbebbebbxbcbegcbnqbqbbbbbibbckbbcbbbcebccbccccbcqbbbbbgqbjbbbbbbbbbtbbbbbbbqbcbbccxbbbbcbcbbbcbbbcbcqcqqbgbbbbbcbbbbbbjtqqqbbcbcjbjcbbcbjqbccbbcbibbbbbcbcbbbbbbqqcjbbrbqbbbbcbbqbbbbbbbcbbbjbbbcqcbqbbbbbcbbtbbbbbtbbcbbbbbqbbcbbtrbbbbbbbbcbcccbccbccbbqqbbbbbcqbbbbbbbcbtbgibbbbbrqbbxbpbbbbbbqbbbcbxqcxcbcbbttbgxbbbccccqbbcvrbbcbbbvbbbqqcbbbbbkbbcbfcbbbbcbbbucbcbqpcbybrbbbbbbbbbbcbbcbbbcbnibbbbcbbbcbbbqbbvbbgkqcrbbbbxbjbbcbbbjbqbbbbcbbbzbccbbbbcbbbqbbbbcbcbbbbbrbcbbycbcbbbbrcjcnbbqbbbbbbncjbrbbcjbbobbqbbbqccbcbvcbbbbqbbcbbccbrbbbccjbcbbibbbjqbbbxbqbbbbrbbbbbbcbpbrqbbcqbcbccctbcqcbmbbbbbcbbcbbcbtbccbbbjbqcbcbbtbbdcbbjbcbcbrbbbbcbcbbbbbbbbbqbbbbbbbbbbqqbbbbbbqbbqbbbbbcrbbbbcbcbbbcbqbcbbbbbbqbbbccbgbbbcqcbccbbbcybbbcbcgcbbcbbjbbbbbjcbcbqbercbjcbbbbbbpbqbbcbbbbbqqvbcbbbbcqbbccgbccqbqbbbcbbbbbbbbqbcbtcbqqbcbqqcbbxbbbbcdbbbbqcvbbqbbqkbbbbbcbbbcqqbbbckcbbqbbbbbcqbbqrbjbbbbbbbqcbccrqbbbjccbbcbbbjrbbbccbbcbcbrcbcxbbnbnbbbbbcbbbbbcbbbbbbjbbbbbcbbccccbcqjbmbbbbbbbqjbbbcqbrbbbkqbbbbqbbybbcqbbjbxbbbbbcbcqbqbbtcqxbcbvbbbbcbbbbbqcqbbbcbbbccbbbnbnccbbbbcbcrcbbcbcjbbbckqcbbcbcbcnbbbcbbbbbbbbbbbcjbbvbbcbbbcbbbqkbbbtbqbrqxcbbjbbcbbbbbccbbbjebbbcbbbxccbbbcbbbxbbxbcbbbcbbdbjbbjcbbcbbbxbbbqicbbbbbbccbbbcnbbbbjcbmcbbbbccbbgbwbbbbycbbbbrcbccbcbbbkdbcbcbbbbbqbbbbbbbbbbbbbndbbbbdcqbbcqqcqbcbbjbcbbrbbbcnbbbqqjbbbbcbbcbbbnbcbbbbbbbcqbbbbbicbcbxmbbbbbvcckbbbccbtbbbbbbbbbtbbbcqcbbbbtbbbbbbbbbbqcbjbbbqbqcbcbbkbbbtbcbbbbbbxcbbkbbbcbrbbcbbqbcbbcbbbbbbbbjjcqbbbqccbbbcbbbbqbrtbbcbbbdnbcbcbbccbbbbbbcybbbbbbcvbbsqbbbbbbcbbbccbbqbbbqbtqckdbbbcibcbbbqbjrqbybbbbmbbbtrbbibvg"
)
);



